import type { Metadata } from "next";
import { Nunito, Roboto, } from "next/font/google";
import "./globals.css";



const nunitoFonts = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const robotoFonts = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Github Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoFonts} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
