import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../styles/globals.css";

import { LayoutType } from "../types/type";
import { Nav } from "../layouts/Nav";

const nunitoFonts = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Github Blog",
  description: "Generated by create next app",
};

const RootLayout: LayoutType = ({ children }) => (
  <html lang="en">
    <body className={`${nunitoFonts.className} antialiased bg-body`}>
      <Nav />
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;
